server:
  port: '8000'

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

  application:
    name: hackathon-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    name: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres

jwt:
  signing:
    key: jwtsigningtestkey
  authorities:
    key: roles
  token:
    validity: '600'
    refresh:
      validity: '1800'


super-admin:
  username:  super_admin
  password:  Super1@hack

razorpay:
  key: rzp_test_l9G0lMZoMpqZ7W
  secret: s5pkHf5aNlCRWSzxVB7U2sy0

#management:
#    endpoints:
#      web:
#        exposure:
#          include: '*'
