package com.hackathon.elitecoders.auth.constants;

public class ConfigConstants {

    /* NOTE: Do Not Edit this file. */

    public static int THOUSAND = 1000;

    public static String ACCESS_CONTROL_ALLOW_ORIGIN = "*";

    public static String ACCESS_CONTROL_ALLOW_CREDENTIALS = "true";

    public static String ACCESS_CONTROL_ALLOW_METHODS = "POST, GET, PUT, PATCH, OPTIONS, DELETE";

    public static String ACCESS_CONTROL_ALLOW_HEADERS = "X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers";

    public static String ACCESS_CONTROL_MAX_AGE = "3600";

    public static String EMPTY_STRING = "";

    public static String COMMA = ",";

    public static String ROLE_ = "ROLE_";

    public static String UNAUTHORIZED = "Unauthorized";

    public static String MESSAGE = "message";

    public static String NO_ERROR_MESSAGE = "No error message found.";

    public final static String AUTHORIZATION = "Authorization";

    public final static String BEARER = "Bearer";

    /* NOTE: Do Not Edit this file. */

}
